name: ACR Credentials Debug

on:
  push:
    branches: [ main ]

jobs:
  debug-acr:
    runs-on: ubuntu-latest

    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME:     ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD:     ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build tiny test image
        run: |
          cat << 'EOF' > Dockerfile.test
          FROM busybox
          CMD ["echo", "hello from ACR test"]
          EOF
          docker build \
            -t $REGISTRY_LOGIN_SERVER/acr-test:latest \
            -f Dockerfile.test \
            .

      - name: Push test image
        run: |
          docker push $REGISTRY_LOGIN_SERVER/acr-test:latest

      - name: Pull test image
        run: |
          docker pull $REGISTRY_LOGIN_SERVER/acr-test:latest

      - name: Run test image
        run: |
          docker run --rm $REGISTRY_LOGIN_SERVER/acr-test:latest
