name: Build & Deploy to Azure Container Instance

on:
  push:
    branches:
      - main

env:
  # Gebruik hier alleen secrets, geen regels of lege regels
  RESOURCE_GROUP:        ${{ secrets.RESOURCE_GROUP }}
  LOCATION:              ${{ secrets.LOCATION }}
  CONTAINER_NAME:        ${{ secrets.CONTAINER_NAME }}
  SHARE_NAME:            ${{ secrets.SHARE_NAME }}
  STORAGE_ACCOUNT_NAME:  ${{ secrets.STORAGE_ACCOUNT_NAME }}
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  REPOSITORY_NAME:       ${{ secrets.REPOSITORY_NAME }}
  IMAGE_TAG:             ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trim newlines uit secrets
        run: |
          for var in RESOURCE_GROUP LOCATION CONTAINER_NAME SHARE_NAME STORAGE_ACCOUNT_NAME; do
            echo "$var=$(echo "${!var}" | tr -d '\r\n')" >> $GITHUB_ENV
          done

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      # JSON met clientId, clientSecret, tenantId, subscriptionId

      - name: Zorg dat Resource Group bestaat
        run: az group create --name "$RESOURCE_GROUP" --location "$LOCATION"

      - name: Zorg dat Azure File Share bestaat
        run: |
          az storage share create \
            --account-name "$STORAGE_ACCOUNT_NAME" \
            --account-key  "${{ secrets.STORAGE_ACCOUNT_KEY }}" \
            --name          "$SHARE_NAME" \
          || echo "Share bestond al, ga door…"

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}

      - name: Delete bestaande ACI (indien aanwezig)
        run: |
          az container delete \
            --resource-group "$RESOURCE_GROUP" \
            --name           "$CONTAINER_NAME" \
            --yes \
          || echo "Geen oude container om te verwijderen."

      - name: Deploy naar Azure Container Instance
        run: |
          az container create \
            --resource-group                 "$RESOURCE_GROUP" \
            --location                       "$LOCATION" \
            --name                           "$CONTAINER_NAME" \
            --image                          "${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}" \
            --registry-login-server          "$REGISTRY_LOGIN_SERVER" \
            --registry-username              "${{ secrets.REGISTRY_USERNAME }}" \
            --registry-password              "${{ secrets.REGISTRY_PASSWORD }}" \
            --dns-name-label                 "$CONTAINER_NAME" \
            --ports                          3000 \
            --cpu                            1 \
            --memory                         1.5 \
            --os-type                        Linux \
            --azure-file-volume-share-name   "$SHARE_NAME" \
            --azure-file-volume-account-name "$STORAGE_ACCOUNT_NAME" \
            --azure-file-volume-account-key  "${{ secrets.STORAGE_ACCOUNT_KEY }}" \
            --azure-file-volume-mount-path   /mnt/azfile \
            --restart-policy                 Always
